language: python
matrix:
  include:
    - name: "Python 2.7.14 on macOS 10.13"
      os: osx
      osx_image: xcode9.3  # Python 2.7.14_2 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python --version
        - pip install -U pip
        - python -m pip install --upgrade pip
        - pip install pytest --user
      install: pip install -r requirements.txt --user
      script: python -m pytest
    - name: "Python 3.6.5 on macOS 10.13"
      os: osx
      osx_image: xcode9.4  # Python 3.6.5 running on macOS 10.13
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      install: pip3 install -r requirements.txt --user
      script: python3 -m pytest
    - name: "Python 3.7.3 on macOS 10.14"
      os: osx
      osx_image: xcode10.2  # Python 3.7.3 running on macOS 10.14.3
      language: shell       # 'language: python' is an error on Travis CI macOS
      before_install:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
      install: pip3 install -r requirements.txt --user
      script: python3 -m pytest
    #  ====== WINDOWS =========
    - name: "Python 2.7 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell # 'language: python' errors Travis CI Windows
      before_install:
        - choco install python2 --no-progress
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
      install: pip install -r requirements.txt --user
      script: python -m pytest
      env: PATH=/c/Python27:/c/Python27/Scripts:$PATH
    - name: "Python 3.5.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.5.4 --no-progress
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
      install: pip install -r requirements.txt --user
      script: python -m pytest
      env: PATH=/c/Python35:/c/Python35/Scripts:$PATH
    - name: "Python 3.6.8 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8 --no-progress
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
      install: pip install -r requirements.txt --user
      script: python -m pytest
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.4 on Windows"
      os: windows           # Windows 10.0.17134 N/A Build 17134
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.4 --no-progress
        - python --version
        - python -m pip install --upgrade pip
        - pip install --upgrade pytest
      install: pip install -r requirements.txt --user
      script: python -m pytest
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
